### ISSUE TITLE
請問slack 要怎麼設鬧鐘? 

### ISSUE THREAD

**Issue by creatopgrace** [creatop/Subject-Asked-Gua#1]

**Comment by JaeChen** [comment]
![1Slack - Do Not Disturb](https://cloud.githubusercontent.com/assets/20034672/16407171/e9123dd0-3d44-11e6-91fb-529ab8d40e8b.jpg)

**Comment by creatopgrace** [comment]
恩.... ? @JaeChen 那個不式提示訊息的sitting嗎?  
我想要像google日歷那種行程提醒的鬧鐘~

**Comment by creatoppinky65** [comment]
![img1](https://cloud.githubusercontent.com/assets/18433907/16438031/8a5f6bec-3dde-11e6-99bb-8f01f6c58bd7.jpg)
![img2](https://cloud.githubusercontent.com/assets/18433907/16438034/8ef2d93c-3dde-11e6-8d00-8e984b0e2817.jpg)

**Comment by creatopgrace** [comment]
感謝大神解答~~~   
不過好像對方如果沒有裝外掛  他不會跳視窗
